#!/bin/bash

set -euxo pipefail

FILES=()

# The never spoken missing file
FILES+=("apb_intf.sv")

# $(ariane_pkg) in Makefile
FILES+=("include/riscv_pkg.sv")
FILES+=("src/riscv-dbg/src/dm_pkg.sv")
FILES+=("include/ariane_pkg.sv")
FILES+=("include/std_cache_pkg.sv")
FILES+=("include/wt_cache_pkg.sv")
FILES+=("src/axi/src/axi_pkg.sv")
FILES+=("src/register_interface/src/reg_intf.sv")
FILES+=("src/register_interface/src/reg_intf_pkg.sv")
FILES+=("include/axi_intf.sv")
FILES+=("tb/ariane_soc_pkg.sv")
FILES+=("include/ariane_axi_pkg.sv")
FILES+=("src/fpu/src/fpnew_pkg.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv")

# $(src) in Makefile
FILES+=("src/alu.sv")
FILES+=("src/amo_buffer.sv")
FILES+=("src/ariane_regfile_ff.sv")
FILES+=("src/ariane.sv")
FILES+=("src/axi_adapter.sv")
FILES+=("src/axi_shim.sv")
FILES+=("src/branch_unit.sv")
FILES+=("src/commit_stage.sv")
FILES+=("src/compressed_decoder.sv")
FILES+=("src/controller.sv")
FILES+=("src/csr_buffer.sv")
FILES+=("src/csr_regfile.sv")
FILES+=("src/decoder.sv")
FILES+=("src/ex_stage.sv")
FILES+=("src/fpu_wrap.sv") # huh???
FILES+=("src/id_stage.sv")
FILES+=("src/instr_realign.sv")
FILES+=("src/issue_read_operands.sv")
FILES+=("src/issue_stage.sv")
FILES+=("src/load_store_unit.sv")
FILES+=("src/load_unit.sv")
FILES+=("src/mmu.sv")
FILES+=("src/multiplier.sv")
FILES+=("src/mult.sv")
FILES+=("src/perf_counters.sv")
FILES+=("src/ptw.sv")
FILES+=("src/re_name.sv")
FILES+=("src/scoreboard.sv")
FILES+=("src/serdiv.sv")
FILES+=("src/store_buffer.sv")
FILES+=("src/store_unit.sv")
FILES+=("src/tlb.sv")
FILES+=("src/fpu/src/fpnew_cast_multi.sv")
FILES+=("src/fpu/src/fpnew_classifier.sv")
FILES+=("src/fpu/src/fpnew_divsqrt_multi.sv")
FILES+=("src/fpu/src/fpnew_fma_multi.sv")
FILES+=("src/fpu/src/fpnew_fma.sv")
FILES+=("src/fpu/src/fpnew_noncomp.sv")
FILES+=("src/fpu/src/fpnew_opgroup_block.sv")
FILES+=("src/fpu/src/fpnew_opgroup_fmt_slice.sv")
FILES+=("src/fpu/src/fpnew_opgroup_multifmt_slice.sv")
FILES+=("src/fpu/src/fpnew_rounding.sv")
FILES+=("src/fpu/src/fpnew_top.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv")
FILES+=("src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv")
FILES+=("src/frontend/bht.sv")
FILES+=("src/frontend/btb.sv")
FILES+=("src/frontend/frontend.sv")
FILES+=("src/frontend/instr_queue.sv")
FILES+=("src/frontend/instr_scan.sv")
FILES+=("src/frontend/ras.sv")
FILES+=("src/cache_subsystem/amo_alu.sv")
FILES+=("src/cache_subsystem/cache_ctrl.sv")
FILES+=("src/cache_subsystem/miss_handler.sv")
FILES+=("src/cache_subsystem/std_cache_subsystem.sv")
FILES+=("src/cache_subsystem/std_icache.sv")
FILES+=("src/cache_subsystem/std_nbdcache.sv")
FILES+=("src/cache_subsystem/tag_cmp.sv")
FILES+=("src/cache_subsystem/wt_axi_adapter.sv")
FILES+=("src/cache_subsystem/wt_cache_subsystem.sv")
FILES+=("src/cache_subsystem/wt_dcache_ctrl.sv")
FILES+=("src/cache_subsystem/wt_dcache_mem.sv")
FILES+=("src/cache_subsystem/wt_dcache_missunit.sv")
FILES+=("src/cache_subsystem/wt_dcache.sv")
FILES+=("src/cache_subsystem/wt_dcache_wbuffer.sv")
FILES+=("src/cache_subsystem/wt_icache.sv")
FILES+=("src/cache_subsystem/wt_l15_adapter.sv")
FILES+=("bootrom/bootrom.sv")
FILES+=("src/clint/axi_lite_interface.sv")
FILES+=("src/clint/clint.sv")
FILES+=("fpga/src/axi2apb/src/axi2apb_64_32.sv")
FILES+=("fpga/src/axi2apb/src/axi2apb.sv")
FILES+=("fpga/src/axi2apb/src/axi2apb_wrap.sv")
FILES+=("fpga/src/apb_timer/apb_timer.sv")
FILES+=("fpga/src/apb_timer/timer.sv")
FILES+=("fpga/src/axi_slice/src/axi_ar_buffer.sv")
FILES+=("fpga/src/axi_slice/src/axi_aw_buffer.sv")
FILES+=("fpga/src/axi_slice/src/axi_b_buffer.sv")
FILES+=("fpga/src/axi_slice/src/axi_r_buffer.sv")
FILES+=("fpga/src/axi_slice/src/axi_single_slice.sv")
FILES+=("fpga/src/axi_slice/src/axi_slice.sv")
FILES+=("fpga/src/axi_slice/src/axi_slice_wrap.sv")
FILES+=("fpga/src/axi_slice/src/axi_w_buffer.sv")
FILES+=("src/axi_node/src/apb_regs_top.sv")
FILES+=("src/axi_node/src/axi_address_decoder_AR.sv")
FILES+=("src/axi_node/src/axi_address_decoder_AW.sv")
FILES+=("src/axi_node/src/axi_address_decoder_BR.sv")
FILES+=("src/axi_node/src/axi_address_decoder_BW.sv")
FILES+=("src/axi_node/src/axi_address_decoder_DW.sv")
FILES+=("src/axi_node/src/axi_AR_allocator.sv")
FILES+=("src/axi_node/src/axi_AW_allocator.sv")
FILES+=("src/axi_node/src/axi_BR_allocator.sv")
FILES+=("src/axi_node/src/axi_BW_allocator.sv")
FILES+=("src/axi_node/src/axi_DW_allocator.sv")
FILES+=("src/axi_node/src/axi_multiplexer.sv")
FILES+=("src/axi_node/src/axi_node_arbiter.sv")
FILES+=("src/axi_node/src/axi_node_intf_wrap.sv")
FILES+=("src/axi_node/src/axi_node.sv")
FILES+=("src/axi_node/src/axi_node_wrap_with_slices.sv")
FILES+=("src/axi_node/src/axi_regs_top.sv")
FILES+=("src/axi_node/src/axi_request_block.sv")
FILES+=("src/axi_node/src/axi_response_block.sv")
FILES+=("src/axi_riscv_atomics/src/axi_res_tbl.sv")
FILES+=("src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv")
FILES+=("src/axi_riscv_atomics/src/axi_riscv_amos.sv")
FILES+=("src/axi_riscv_atomics/src/axi_riscv_atomics.sv")
FILES+=("src/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv")
FILES+=("src/axi_riscv_atomics/src/axi_riscv_lrsc.sv")
FILES+=("src/axi_riscv_atomics/src/axi_riscv_lrsc_wrap.sv")
FILES+=("src/axi_mem_if/src/axi2mem.sv")
FILES+=("src/rv_plic/rtl/rv_plic_target.sv")
FILES+=("src/rv_plic/rtl/rv_plic_gateway.sv")
FILES+=("src/rv_plic/rtl/plic_regmap.sv")
FILES+=("src/rv_plic/rtl/plic_top.sv")
FILES+=("src/riscv-dbg/src/dmi_cdc.sv")
FILES+=("src/riscv-dbg/src/dmi_jtag.sv")
FILES+=("src/riscv-dbg/src/dmi_jtag_tap.sv")
FILES+=("src/riscv-dbg/src/dm_csrs.sv")
FILES+=("src/riscv-dbg/src/dm_mem.sv")
FILES+=("src/riscv-dbg/src/dm_sba.sv")
FILES+=("src/riscv-dbg/src/dm_top.sv")
FILES+=("src/riscv-dbg/debug_rom/debug_rom.sv")
FILES+=("src/register_interface/src/apb_to_reg.sv")
FILES+=("src/axi/src/axi_multicut.sv")
FILES+=("src/common_cells/src/deprecated/generic_fifo.sv")
FILES+=("src/common_cells/src/deprecated/pulp_sync.sv")
FILES+=("src/common_cells/src/deprecated/find_first_one.sv")
FILES+=("src/common_cells/src/rstgen_bypass.sv")
FILES+=("src/common_cells/src/rstgen.sv")
FILES+=("src/common_cells/src/stream_mux.sv")
FILES+=("src/common_cells/src/stream_demux.sv")
FILES+=("src/common_cells/src/exp_backoff.sv")
FILES+=("src/util/axi_master_connect.sv")
FILES+=("src/util/axi_slave_connect.sv")
FILES+=("src/util/axi_master_connect_rev.sv")
FILES+=("src/util/axi_slave_connect_rev.sv")
FILES+=("src/axi/src/axi_cut.sv")
FILES+=("src/axi/src/axi_join.sv")
FILES+=("src/axi/src/axi_delayer.sv")
FILES+=("src/axi/src/axi_to_axi_lite.sv")
FILES+=("src/fpga-support/rtl/SyncSpRamBeNx64.sv")
FILES+=("src/common_cells/src/unread.sv")
FILES+=("src/common_cells/src/sync.sv")
FILES+=("src/common_cells/src/cdc_2phase.sv")
FILES+=("src/common_cells/src/spill_register.sv")
FILES+=("src/common_cells/src/sync_wedge.sv")
FILES+=("src/common_cells/src/edge_detect.sv")
FILES+=("src/common_cells/src/stream_arbiter.sv")
FILES+=("src/common_cells/src/stream_arbiter_flushable.sv")
FILES+=("src/common_cells/src/deprecated/fifo_v1.sv")
FILES+=("src/common_cells/src/deprecated/fifo_v2.sv")
FILES+=("src/common_cells/src/fifo_v3.sv")
FILES+=("src/common_cells/src/lzc.sv")
FILES+=("src/common_cells/src/popcount.sv")
FILES+=("src/common_cells/src/rr_arb_tree.sv")
FILES+=("src/common_cells/src/deprecated/rrarbiter.sv")
FILES+=("src/common_cells/src/stream_delay.sv")
FILES+=("src/common_cells/src/lfsr_8bit.sv")
FILES+=("src/common_cells/src/lfsr_16bit.sv")
FILES+=("src/common_cells/src/counter.sv")
FILES+=("src/common_cells/src/shift_reg.sv")
FILES+=("src/tech_cells_generic/src/pulp_clock_gating.sv")
FILES+=("src/tech_cells_generic/src/cluster_clock_inverter.sv")
FILES+=("src/tech_cells_generic/src/pulp_clock_mux2.sv")
# FILES+=("tb/ariane_testharness.sv")
# FILES+=("tb/ariane_peripherals.sv")
# FILES+=("tb/common/uart.sv")
# FILES+=("tb/common/SimDTM.sv")
# FILES+=("tb/common/SimJTAG.sv")

# $(verilate_command) in Makefile
FILES+=("src/util/sram.sv")
# FILES+=("tb/common/mock_uart.sv")

if [ "$(basename "$0")" = "sv2v.sh" ]; then
    sv2v \
        -I src/axi_node \
        -I src/common_cells/include/ \
        -D WT_DCACHE \
        -D VERILATOR \
        "${FILES[@]}" >sv2v-result.v
elif [ "$(basename "$0")" = "sv2v-cleanup.sh" ]; then
    I=0
    while [ "$I" -lt "${#FILES[@]}" ]; do
        truncate -s 0 "${FILES[$I]}"
        I="$((I+1))"
    done
else
    echo 'Unknown $0:'
    printf '%s\n' "$0" "$@"
fi
